#!/usr/bin/env python3
#-*- encoding: utf-8 -*-

import argparse
import codecs


p = argparse.ArgumentParser()
p.add_argument('string')
args = p.parse_args()

print(args.string.encode('latin1').decode('utf8'))
